---
title: "R Notebook"
output: html_notebook
---


```{r}
library(fma)
library(psych)
#library(lubridate)
library(party)
library(randomForest)
library(caret)
library(tseries)
#library(data.table)
library(Boruta)
library(plyr)
library(dplyr)
#library(pROC)
library(Metrics)
library(imputeTS)
#load libraries
pkgs <- c('tidyverse', 'corrplot', 'magrittr', 'zoo', 'RColorBrewer', 'gridExtra','MASS')
invisible(lapply(pkgs, require, character.only = T))
```

```{r}
path = 'C:/Users/parth/Desktop/Git/Projects/DengAI/Data/'
train_df <- read.csv(paste(path,'dengue_features_train.csv',sep = ""),stringsAsFactors = F)
print(c(nrow(train_df),ncol(train_df)))
head(train_df)

test_df <- read.csv(paste(path,'dengue_features_test.csv',sep = ""),stringsAsFactors = F)
print(c(nrow(test_df),ncol(test_df)))
head(test_df)

combine_df <- rbind(train_df,test_df)
print(c(nrow(combine_df),ncol(combine_df)))
head(combine_df)
```

```{r}
imp <- na.kalman(combine_df[,5:24])
combine_df[,5:24] <- imp

sum(is.na(combine_df))
rm("imp")
```

```{r}
train_label_df <- read.csv(paste(path,'dengue_labels_train.csv',sep = ""),stringsAsFactors = F)
test_label_df <- read.csv(paste(path,'submission_format.csv',sep = ""),stringsAsFactors = F)
combine_label_df <- rbind(train_label_df,test_label_df)
combine_df$total_cases <- combine_label_df$total_cases

train_data_sj <- combine_df[1:1456,] %>% filter(city=='sj')
train_data_iq <- combine_df[1:1456,] %>% filter(city=='iq')

test_data_sj <- combine_df[1457:1872,] %>% filter(city=='sj')
test_data_iq <- combine_df[1457:1872,] %>% filter(city=='iq')

```

```{r}
ts_sj <- ts(train_data_sj$total_cases,start = c(1990,18),end = c(2008,17),frequency = 52)
ts.plot(window(ts_sj,start=1991,end=1995),major.format = "%Y-%m")
# train_data_sj %>%
#   mutate(index = as.numeric(row.names(.))) %>%
#   ggplot(aes(index, total_cases)) +  
#   geom_line(colour = 'dodgerblue') +
#   ggtitle("Total Cases in SJ over Time")
```
```{r}
##From the Benchmark model
features = c("reanalysis_specific_humidity_g_per_kg", "reanalysis_dew_point_temp_k","station_avg_temp_c", "station_min_temp_c")
# qqnorm(train_data_sj$reanalysis_specific_humidity_g_per_kg)
# qqline(train_data_sj$reanalysis_specific_humidity_g_per_kg)
# 
# qqnorm(log(train_data_sj$reanalysis_specific_humidity_g_per_kg+1),main = "log tran")
# qqline(log(train_data_sj$reanalysis_specific_humidity_g_per_kg+1),main = "log tran")

library(xgboost)

sj_dtrain = xgb.DMatrix(as.matrix(train_data_sj[features]), label = train_data_sj$total_cases)
sj_dtest = xgb.DMatrix(as.matrix(test_data_sj[features]))

iq_dtrain = xgb.DMatrix(as.matrix(train_data_iq[features]), label = train_data_iq$total_cases)
iq_dtest = xgb.DMatrix(as.matrix(test_data_iq[features]))

```

```{r}
cv.ctrl = trainControl(method = "repeatedcv", repeats = 1,number = 4, allowParallel=T)

xgb.grid = expand.grid(nrounds = 750,
    eta = c(0.01,0.005,0.001),
    max_depth = c(4,6,8),
    colsample_bytree=c(0,1,10),
    min_child_weight = 2,
    subsample=c(0,0.2,0.4,0.6),
    gamma=0.01)
set.seed(45)
xgb_params = list(
  booster = 'gbtree',
  objective = 'reg:linear',
  colsample_bytree=1,
  eta=0.005,
  max_depth=4,
  min_child_weight=3,
  alpha=0.3,
  lambda=0.4,
  gamma=0.01, # less overfit
  subsample=0.6,
  seed=5,
  silent=TRUE)
#xgb.cv(xgb_params, sj_dtrain, nrounds = 5000, nfold = 4, early_stopping_rounds = 500)
bst_sj = xgb.train(xgb_params,sj_dtrain, nrounds = 1000)
bst_iq = xgb.train(xgb_params,iq_dtrain, nrounds = 1000)
```

```{r}
test_xgb_yhat_sj <- round(predict(bst_sj,newdata = sj_dtest,type = "raw"))
test_xgb_yhat_iq <- round(predict(bst_iq,newdata = iq_dtest,type = "raw"))
test_xgb_yhat <- c(test_xgb_yhat_sj,test_xgb_yhat_iq)
submission <- read.csv(paste(path,'submission_format.csv',sep = ""),stringsAsFactors = F)
submission$total_cases <- test_xgb_yhat
head(submission)
write.csv(submission,paste(path,'submission_xgboost_1.csv',sep = ""),row.names=F,quote = F)
```

```{r}
# par(mfrow=c(1,2))
plot(train_data_sj$total_cases,type="l",xlim=c(100,300))
plot(test_xgb_yhat_sj,type="l",ylim=c(0,450),xlim=c(100,300),main='predicted')
# library(smooth)
# library(Mcomp)
#plot(sma(test_xgb_yhat_sj),type="l",ylim=c(0,450),,xlim=c(100,300),main='sma')
#plot(log(test_xgb_yhat_sj),type="l",ylim=c(0,450),,xlim=c(100,300),main='predicted')
fit_sj <- sma(test_xgb_yhat_sj)
fit_iq <- sma(test_xgb_yhat_iq)
test_xgb_yhat_sma <- c(as.numeric(fit_sj$fitted),as.numeric(fit_iq$fitted))
plot(test_xgb_yhat_sma,type="l",ylim=c(0,450),main="sma")

submission <- read.csv(paste(path,'submission_format.csv',sep = ""),stringsAsFactors = F)
submission$total_cases <- round(test_xgb_yhat_sma)
head(submission)
write.csv(submission,paste(path,'submission_xgboost_2.csv',sep = ""),row.names=F,quote = F)

```

